version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: severino_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
  bots:
    build:
      context: .
      dockerfile: Dockerfile.bots
    container_name: severino_bots
    restart: unless-stopped
    env_file:
      - bot/.env
    ports:
      - "3080:3080"
      - "4580:4580"
    command: sh -c "node bot/src/index.js"
    depends_on:
      - frontend
